version: '3'

services:
  woodpecker-server:
    image: quay.io/woodpeckerci/woodpecker-server:next
    ports:
      - 8000:8000
    networks:
      - woodpecker
    volumes:
      - /var/lib/woodpecker:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=laszlocph
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=${WOODPECKER_GITHUB_CLIENT}
      - WOODPECKER_GITHUB_SECRET=${WOODPECKER_GITHUB_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

  woodpecker-agent:
    depends_on:
      woodpecker-server:
        condition: service_healthy
    image: quay.io/woodpeckerci/woodpecker-agent:next
    networks:
      - woodpecker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_MAX_WORKFLOWS=2

networks:
  woodpecker:
