version: '2'

services:
  woodpecker-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: woodpeckerci/woodpecker-server:local
    ports:
      - 8000:8000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=laszlocph
      - WOODPECKER_HOST=${HOST}
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=${GITHUB_CLIENT}
      - WOODPECKER_GITHUB_SECRET=${GITHUB_SECRET}
      - WOODPECKER_SECRET=${WOODPECKER_SECRET}
  woodpecker-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    image: woodpeckerci/woodpecker-agent:local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=drone-server:9000
      - WOODPECKER_SECRET=${WOODPECKER_SECRET}
      - WOODPECKER_MAX_PROCS=2
