blank_issues_enabled: true
contact_links:
  - name: Start a discussion
    about: Our preferred starting point if you have any questions, suggestions or feature requests.
    url: https://github.com/woodpecker-ci/woodpecker/discussions/new/choose
  - name: Frequently Asked Questions
    url: https://woodpecker-ci.org/faq
    about: Check the FAQs for common questions.
