site_name: Woodpecker
repo_name: 'laszlocph/woodpecker'
repo_url: 'https://github.com/laszlocph/woodpecker'
edit_uri: 'blob/master/docs/docs/'
copyright: 'Creative Commons Attribution-ShareAlike 4.0 International Public License.<br />It is a derivative work of the https://github.com/drone/docs git repository'
nav:
  - Home: index.md
  - Server Setup: server-setup.md
  - Getting Started: getting-started.md
  - Pipelines: pipeline.md
  - Services: services.md
  - Plugins: plugins.md
  - Environment Variables: environment-variables.md
  - Secrets: secrets.md
  - Volumes: volumes.md
  - Matrix Builds: matrix-builds.md
  - Multi Pipeline Builds: multi-pipeline.md
theme:
  name: 'material'
  logo: 'images/favicon.svg'
  favicon: 'images/favicon.svg'
  palette:
    primary: 'green'
    accent: 'red'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite

extra:
  social:
    - type: globe
      link: http://woodpecker.laszlo.cloud
    - type: twitter
      link: https://twitter.com/laszlocph
