name: Go
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.4

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/pkg/mod/github.com/laszlocph/woodpecker

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
      env:
        GOPATH: /home/runner/work/woodpecker/go

    - name: Test
      with:
        path: go/pkg/mod/github.com/laszlocph/woodpecker
      env:
        GOPATH: /home/runner/work/woodpecker/go
        GO111MODULE: on      
      run: |
        go get -u golang.org/x/tools/cmd/cover
        go get -u golang.org/x/net/context
        go get -u golang.org/x/net/context/ctxhttp
        go get -u github.com/golang/protobuf/proto
        go get -u github.com/golang/protobuf/protoc-gen-go
        go test -cover $(go list ./... | grep -v /vendor/)


    - name: Build
      run: ./.drone.sh
      env:
        GOPATH: /home/runner/work/woodpecker/go
